services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chien1472004
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/socialnetwork
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: chien1472004
      VIDEO_UPLOAD_DIR: /app/uploads
      VIDEO_STREAM_DIR: /app/streams
      SPRING_MAIL_USERNAME: chien1472k4@gmail.com
      SPRING_MAIL_PASSWORD: ycpz woln cqtl ygde
      GOOGLE_CLIENT_SECRET: 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
      REDIRECT_GOOGLE: http://localhost:8080/api/login/oauth2/code/google
      JWT_SECRET: qazxsdrftgsbhdasgbhnjfksijdfbdfdfdfsdfsfsdffsdfsdfsdfsdgfgjdjhukdmyhargadsgsdfgdfgsgerghfbsdfdsstdsvsdgsdgsdgshfvbdrg
    volumes:
      - ./uploads:/app/uploads
      - ./streams:/app/streams
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
